# Generated by Django 3.0.5 on 2020-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Passenger',
        ),
    ]
