# Generated by Django 3.0.5 on 2020-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200418_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Master', 'Master'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=10),
        ),
    ]
