# Generated by Django 3.0.5 on 2020-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200419_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='cabin',
            new_name='Cabin',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='ticket',
            new_name='Ticket',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='embarked',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='sex',
        ),
        migrations.AddField(
            model_name='passenger',
            name='Embarked',
            field=models.CharField(choices=[('Cherbourg', 'C'), ('Queenstown', 'Q'), ('Southampton', 'S')], default='S', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='Sex',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Pclass',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Master', 'Master'), ('Mrs', 'Mrs.'), ('Miss', 'Miss.')], max_length=10),
        ),
    ]
