# Generated by Django 3.0.5 on 2020-04-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200419_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='Pclass',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
